/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.josescalia.swingrss.gui;

import java.awt.BorderLayout;
import javax.swing.*;

import org.apache.log4j.Logger;
import org.josescalia.swingrss.gui.form.AboutForm;
import org.josescalia.swingrss.gui.form.LandFForm;
import org.josescalia.swingrss.gui.form.RssFeedForm;
import org.josescalia.swingrss.gui.form.RssReaderForm;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author Josescalia
 */
public class MainApp extends javax.swing.JFrame {
    static Logger logger = Logger.getLogger(MainApp.class.getName());
    public static ApplicationContext ctx;
    /**
     * Creates new form MainApp
     */
    public MainApp() {
        ctx = new ClassPathXmlApplicationContext("rssReaderApplicationContext.xml");
        initComponents();
    }

    public void setLookAndFeel(String lfClassName){
        try {
            UIManager.setLookAndFeel(lfClassName);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        new MainApp().setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblPanelAction = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnRssReader = new javax.swing.JMenuItem();
        mnSuggestedFeed = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnLFSetting = new javax.swing.JMenuItem();
        mnAboutBox = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rss Reader");
        setIconImage(new ImageIcon(getClass().getResource("/icons/rss-icon.png")).getImage());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 665, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Created By: Josescalia@2012");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPanelAction, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 941, Short.MAX_VALUE)
                                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPanelAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jMenu1.setText("File");

        mnRssReader.setText("Rss Viewer");
        mnRssReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRssReaderActionPerformed(evt);
            }
        });
        jMenu1.add(mnRssReader);

        mnSuggestedFeed.setText("Suggested Feed");
        mnSuggestedFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuggestedFeedActionPerformed(evt);
            }
        });
        jMenu1.add(mnSuggestedFeed);
        jMenu1.add(jSeparator1);

        mnExit.setText("Quit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Setting");

        mnLFSetting.setText("Look And Feel");
        mnLFSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLFSettingActionPerformed(evt);
            }
        });
        jMenu2.add(mnLFSetting);

        mnAboutBox.setText("About");
        mnAboutBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutBoxActionPerformed(evt);
            }
        });
        jMenu2.add(mnAboutBox);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    
    private void mnRssReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRssReaderActionPerformed
        removePanelFromMain();
        RssReaderForm frm = ctx.getBean(RssReaderForm.class);
        frm.showForm();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(frm);
        mainPanel.validate();
        lblPanelAction.setText("Rss Reader");
    }//GEN-LAST:event_mnRssReaderActionPerformed

    private void mnSuggestedFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuggestedFeedActionPerformed
        removePanelFromMain();
        RssFeedForm form = ctx.getBean(RssFeedForm.class);
        form.showForm();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(form);
        mainPanel.validate();
        lblPanelAction.setText("Editing Suggested Feed");
    }//GEN-LAST:event_mnSuggestedFeedActionPerformed

    private void mnAboutBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutBoxActionPerformed
        removePanelFromMain();
        AboutForm form = ctx.getBean(AboutForm.class);
        form.showForm();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(form);
        mainPanel.validate();
        lblPanelAction.setText("About Swing RssReader Application");
    }//GEN-LAST:event_mnAboutBoxActionPerformed

    private void mnLFSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLFSettingActionPerformed
        removePanelFromMain();
        LandFForm form = ctx.getBean(LandFForm.class);
        form.showForm();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(form);
        mainPanel.validate();
        lblPanelAction.setText("Look and Feel Setting");
    }//GEN-LAST:event_mnLFSettingActionPerformed

    private void removePanelFromMain(){
        if (mainPanel.getComponentCount() > 0) {
            logger.info("Existing component :" + mainPanel.getComponentCount());
            //remove All from MainPanel
            for (int i = 0; i < mainPanel.getComponentCount(); i++) {
                mainPanel.remove(i);
                mainPanel.validate();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                } catch (Exception e) {
                }
                new MainApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblPanelAction;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem mnAboutBox;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnLFSetting;
    private javax.swing.JMenuItem mnRssReader;
    private javax.swing.JMenuItem mnSuggestedFeed;
    // End of variables declaration//GEN-END:variables
}
